version: "1.0"
stages:
  - "build"
steps:
  clone:
    title: Cloning repository...
    stage: build
    type: git-clone
    repo: '${{CF_REPO_OWNER}}/${{CF_REPO_NAME}}'
    revision: '${{CF_REVISION}}'
    git: github
  build:
    title: Building pom
    stage: build
    image: openjdk:8-alpine
    commands:
      - ./mvnw clean package
